### ISSUE TITLE
Roadmap for future work

### ISSUE THREAD

**Issue by sg-s** [sg-s/stg-embedding#6]
- [x] Get all spikes from PD neurons in high-K data
- [x] measure distances using new distance metric in high-K data
- [x] show distance matrix for PD neurons in high K data
- [x] embed using t-SNE 
- [ ] embed using UMAP
